# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: M. Haziq Norazri
title: Physicist | Data Analyst
email: haziq.norazri@gmail.com
#website: http://hibee.ml

# Social links
# twitter_username: facespics
github_username:  haziqnorazri
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: haziqnorazri
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/HaziqNorazri.jpeg
about_content: | # this will include new lines to allow paragraphs
  Conduct data mining, data modeling, statistical analysis, business intelligence gathering, trending and benchmarking. Data analytics supports decisions for high-priority, enterprise initiatives involving IT/product development, customer service improvement, organizational realignment and process reengineering.
  
  Highlights: 
    - Python Programming.
    - SAS Entreprise Guide.
    - Macros VBA Excel. 
    - Big Data Analytics. 
    - TECPLOT360 Visualisation Software.
    - Monte Carlo N-Particle Simulation (MCNP).
   
# More Section
# more_title: A Little More About Me
#more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
